In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import time

# import the two classes containing the algorithms
import scaling
import inference

In [2]:
# generate ranking data from NASCAR2002 dataset
data = pd.read_csv('nascar2002.txt', sep=" ")
nb_items = max(data['DriverID'])
num_race = max(data['Race'])
rankings = ()
for i in range(num_race):
    race_id = i+1
    race = data[data['Race']==race_id]
    ranking = list(race['DriverID']-1)
    rankings = rankings + (tuple(ranking),)

In [3]:
# generate comparison matrix and winning count
A, p = scaling.ranking_to_choice(nb_items,rankings)

# MLE with scaling algorithm
start = time.time()
#A, p = scaling.ranking_to_choice(nb_items,rankings)
scaling_strength, scaled_A, iterations,_ = scaling.iterative_scaling(A,p)
end = time.time()
print('Scaling algorithm converged in ',iterations, 'iterations and took ',end-start,'seconds.')

# MLE with iterative LSR algorithm
start = time.time()
ilsr_strength, iterations,_ = inference.ilsr(nb_items,rankings)
end = time.time()
print('Iterative LSR algorithm converged in ',iterations, 'iterations and took ',end-start,'seconds.')

#MLE with iterative LSR algorithm, convergence on log likelihood
#start = time.time()
#ilsr_strength = inference.ilsr(nb_items,rankings)
#end = time.time()
#print('Iterative LSR algorithm with log-likelihood convergence criterion converged in ',iterations, 'iterations and took ',end-start,'seconds.')

Scaling algorithm converged in  20 iterations and took  0.0030517578125 seconds.
Iterative LSR algorithm converged in  13 iterations and took  0.22899818420410156 seconds.


In [4]:
(m,n) = scaled_A.shape
uniform = np.ones(m)/m
np.dot(scaled_A.T,uniform)-p

array([-1.29186700e-12, -4.65072078e-11, -3.87560053e-11, -4.65071974e-11,
       -2.58373422e-12, -4.13397615e-11, -9.04307011e-12, -2.58373422e-12,
       -4.52153662e-11, -1.29186679e-12, -1.29186700e-12, -4.65071870e-11,
       -4.65072182e-11, -4.52153349e-11, -1.29186722e-12, -9.04306924e-12,
       -3.87560166e-12, -4.52153523e-11, -5.16746845e-12, -1.16268072e-11,
       -9.04306838e-12, -1.29186700e-12, -1.29186705e-11, -1.29186700e-12,
       -2.71292173e-11, -3.87560123e-12, -7.75120246e-12, -2.58373422e-12,
       -1.29186700e-12, -1.29186711e-12, -4.65072182e-11, -4.65072078e-11,
       -4.65072147e-11, -4.65072078e-11, -3.61722770e-11, -1.29186690e-12,
       -4.65071939e-11, -4.39234690e-11, -4.00478609e-11, -1.29186700e-12,
       -4.39234968e-11, -3.87560019e-11, -4.52153592e-11, -2.71292069e-11,
       -4.52153384e-11, -2.58373444e-12, -2.58373422e-12, -4.65072182e-11,
       -4.65071939e-11, -1.29186700e-12, -4.65071939e-11, -4.65071939e-11,
       -4.65071974e-11, -

In [5]:
np.sum(scaled_A,axis=1)

array([1., 1., 1., ..., 1., 1., 1.])

In [6]:
scaling_strength/scaling_strength.sum()

array([0.00294544, 0.0134518 , 0.00903423, 0.01148513, 0.00632024,
       0.00621403, 0.00647339, 0.00213965, 0.00608238, 0.0065    ,
       0.00189386, 0.0137903 , 0.01463798, 0.01268245, 0.00302244,
       0.00388378, 0.00215749, 0.00823203, 0.00220686, 0.00515624,
       0.0083826 , 0.00678157, 0.00531443, 0.00137539, 0.00695257,
       0.00622883, 0.00993915, 0.0062232 , 0.00172276, 0.0017243 ,
       0.01535472, 0.01679538, 0.01179859, 0.00920563, 0.00696894,
       0.00805003, 0.02049299, 0.00968924, 0.00567744, 0.00254749,
       0.00762482, 0.00986116, 0.00721782, 0.00926004, 0.00944684,
       0.00185337, 0.0021319 , 0.01531125, 0.0108887 , 0.00801097,
       0.02348856, 0.01484268, 0.01233173, 0.02741906, 0.00725215,
       0.00494445, 0.00187749, 0.18640456, 0.00569201, 0.01260302,
       0.01614273, 0.01153012, 0.01461678, 0.01260138, 0.00523963,
       0.0230462 , 0.01328302, 0.10955554, 0.00277768, 0.0029409 ,
       0.00527774, 0.01669486, 0.00613762, 0.00728464, 0.00149

In [7]:
ilsr_strength/ilsr_strength.sum()

array([0.00294544, 0.0134518 , 0.00903423, 0.01148513, 0.00632024,
       0.00621403, 0.00647339, 0.00213965, 0.00608238, 0.0065    ,
       0.00189386, 0.0137903 , 0.01463798, 0.01268245, 0.00302244,
       0.00388378, 0.00215749, 0.00823203, 0.00220686, 0.00515624,
       0.0083826 , 0.00678157, 0.00531443, 0.00137539, 0.00695257,
       0.00622883, 0.00993915, 0.0062232 , 0.00172276, 0.0017243 ,
       0.01535472, 0.01679538, 0.01179859, 0.00920563, 0.00696894,
       0.00805003, 0.02049299, 0.00968924, 0.00567744, 0.00254749,
       0.00762482, 0.00986116, 0.00721782, 0.00926004, 0.00944684,
       0.00185337, 0.0021319 , 0.01531125, 0.0108887 , 0.00801097,
       0.02348856, 0.01484268, 0.01233173, 0.02741906, 0.00725215,
       0.00494445, 0.00187749, 0.18640456, 0.00569201, 0.01260302,
       0.01614273, 0.01153012, 0.01461678, 0.01260138, 0.00523963,
       0.0230462 , 0.01328302, 0.10955554, 0.00277768, 0.0029409 ,
       0.00527774, 0.01669486, 0.00613762, 0.00728464, 0.00149

In [8]:
scaling_strength/scaling_strength.sum() - ilsr_strength/ilsr_strength.sum()

array([ 2.37005034e-12,  1.53900261e-11,  1.02349101e-11,  1.50534810e-11,
        4.89895017e-12,  6.96526604e-12,  7.05393469e-12,  2.42412731e-12,
        7.27483178e-12,  7.46479441e-12,  9.53806977e-12,  1.50217443e-11,
        1.61259651e-11,  1.41744550e-11,  3.32247511e-12,  5.88724859e-12,
        2.93049959e-12,  9.33886822e-12,  2.33901700e-12,  5.41061987e-12,
        9.69781547e-12,  7.76969981e-12,  5.93535984e-12,  1.58449924e-12,
        7.75887254e-12,  7.37615698e-12,  2.65483625e-11,  9.45147172e-12,
        2.04372435e-12,  1.92099960e-12,  1.66190429e-11,  1.79727795e-11,
        1.40171451e-11,  1.03702880e-11,  7.72128542e-12,  7.86008585e-12,
        2.28072977e-11,  1.09167241e-11,  6.22511157e-12,  3.13479537e-12,
        8.55211475e-12,  1.08674632e-11,  8.51097318e-12,  1.03131722e-11,
        1.06439198e-11,  2.12540727e-12,  2.44365856e-12,  1.67772810e-11,
        1.24307023e-11,  1.00998983e-11,  2.57264383e-11,  1.61035560e-11,
        1.36630637e-11,  