In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import time

# import the two classes containing the algorithms
import scaling
import inference

In [2]:
A, p = np.load('matA.npy',allow_pickle=True)
A

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.]])

In [3]:
p = np.squeeze(p)
p = p/np.sum(p)
p

array([4.37886800e-03, 1.89333912e-03, 1.02173587e-02, 1.00088411e-02,
       5.81346856e-03, 7.28977263e-03, 1.81743874e-02, 1.23192153e-02,
       1.84079270e-02, 4.51231922e-03, 9.25817806e-03, 1.77656930e-03,
       2.07683454e-03, 1.91836122e-03, 2.23530786e-03, 1.14517824e-02,
       1.03424692e-02, 2.63899778e-02, 1.45962267e-02, 3.58650141e-03,
       6.00530469e-04, 2.65234290e-03, 1.20940164e-03, 2.93592674e-03,
       3.06937795e-03, 3.59484211e-03, 2.64400220e-03, 1.26528433e-02,
       9.59180610e-04, 1.02006773e-02, 1.65562914e-02, 1.01589738e-02,
       2.59395800e-03, 6.75596777e-03, 2.98597094e-03, 6.08871170e-04,
       2.01010893e-03, 2.11186548e-02, 6.61417586e-03, 4.75419954e-04,
       5.75508366e-03, 1.01172703e-02, 5.67167665e-04, 1.49715582e-02,
       5.15455319e-03, 1.76072197e-02, 4.24891988e-01, 3.97851435e-03,
       3.56147931e-03, 3.01432932e-02, 4.75419954e-04, 1.95172402e-03,
       5.51236926e-02, 1.25277328e-02, 2.69738269e-02, 8.09047992e-04,
      

In [44]:
# MLE with scaling algorithm
start = time.time()
#A, p = scaling.ranking_to_choice(nb_items,rankings)
scaling_strength, scaled_A, iterations,_ = scaling.iterative_scaling(A,p)
end = time.time()
print('Scaling algorithm converged in ',iterations, 'iterations and took ',end-start,'seconds.')

Scaling algorithm converged in  158 iterations and took  2.2817628383636475 seconds.


In [45]:
(m,n) = scaled_A.shape
uniform = np.ones(m)/m
np.dot(scaled_A.T,uniform)-p

array([3.49139120e-14, 1.51144288e-14, 8.16915979e-14, 7.97209521e-14,
       4.63457397e-14, 5.81600740e-14, 1.44471241e-13, 9.83189224e-14,
       1.46733320e-13, 3.60371455e-14, 7.38940159e-14, 1.41750760e-14,
       1.65674766e-14, 1.53087178e-14, 1.78494372e-14, 9.13470688e-14,
       8.25797764e-14, 2.10571144e-13, 1.16517906e-13, 2.86264068e-14,
       4.79282412e-15, 2.11740347e-14, 9.65026670e-15, 2.34274405e-14,
       2.45055712e-14, 2.86736780e-14, 2.10864312e-14, 1.00771821e-13,
       7.65414208e-15, 8.13168977e-14, 1.32165112e-13, 8.11642420e-14,
       2.07043584e-14, 5.39160730e-14, 2.38181870e-14, 4.85971940e-15,
       1.60466258e-14, 1.68337566e-13, 5.27876354e-14, 3.79432813e-15,
       4.59337429e-14, 8.07322958e-14, 4.52665249e-15, 1.19381935e-13,
       4.11519777e-14, 1.40432804e-13, 3.42187390e-12, 3.17584500e-14,
       2.83943875e-14, 2.40751863e-13, 3.79524970e-15, 1.55767326e-14,
       4.42812453e-13, 1.00194159e-13, 2.15962664e-13, 6.45750814e-15,
      

In [46]:
np.sum(scaled_A,axis=1)

array([1., 1., 1., ..., 1., 1., 1.])

In [47]:
strength = scaling_strength/scaling_strength.sum()

In [48]:
strength

array([0.00790127, 0.00945408, 0.01057957, 0.01572598, 0.00738477,
       0.01531757, 0.0252985 , 0.01024566, 0.00671597, 0.00782159,
       0.00984616, 0.03399052, 0.022052  , 0.03983143, 0.0041686 ,
       0.01479429, 0.01153146, 0.00840099, 0.03970201, 0.00722172,
       0.00815116, 0.02014438, 0.00609883, 0.02647825, 0.02743074,
       0.01442736, 0.00477104, 0.02707355, 0.01048114, 0.01343148,
       0.01349006, 0.02321892, 0.00413916, 0.01018591, 0.01649368,
       0.00242822, 0.01031754, 0.03175474, 0.00995239, 0.0056048 ,
       0.01026359, 0.01153496, 0.00649525, 0.01348242, 0.00606789,
       0.00644929, 0.01624875, 0.02564724, 0.0306389 , 0.01031583,
       0.00381287, 0.00415342, 0.00576941, 0.00378675, 0.0048701 ,
       0.00653051, 0.01681789, 0.00728466, 0.0054519 , 0.00536414,
       0.00535652, 0.00839096, 0.00926259, 0.0038812 , 0.01103616,
       0.00356548, 0.00051624, 0.02152253, 0.01633869, 0.02507931,
       0.01207357, 0.00241413, 0.0063789 , 0.01868218, 0.01171

In [49]:
policies = ['pretrain_3b',
 'sup4_6b_t.5',
 'sup4_6b',
 'sup4_bo128_rm3',
 'sup4_12b_t0.7',
 'sup4_bo64_rm3',
 'sup4_6b_ppo_rm3_6b_kl15',
 'sup4_ppo_rm3',
 'pretrain_12b_t.5',
 'pretrain_12b',
 'sup4_ppo_rm3_kl2',
 'sup4_6b_ppo_rm4_6b_t.7',
 'sup4_bo256_rm3_6b',
 'sup4_6b_ppo_rm4_6b_t.5',
 'pretrain_xl',
 'sup4_ppo_rm3_kl22',
 'sup4_ppo_rm3_kl6',
 'sup3_6b',
 'sup4_6b_ppo_rm4_6b',
 'sup4_xl_bo64_rouge',
 'sup4_xl_bo16_rm4',
 'sup4_bo128_rm3_6b',
 'sup4_6b_p.9',
 'sup4_xl_bo128_rm4_6b',
 'sup4_xl_bo1024_rm4',
 'sup4_xl_bo64_rm4',
 'sup4_xl_bo512_rouge',
 'sup4_ppo_rm4',
 'sup4_xl_bo8_rm4',
 'sup4_ppo_rm3_kl10',
 'sup3_bo8_rm2',
 'sup3_bo63_rm2',
 'pretrain_6b_t.7',
 'sup4_3b',
 'sup4_xl_bo128_rm4',
 'sup4_6b_t1',
 'sup4_6b_t.3',
 'sup4_6b_ppo_rm4_6b_kl14',
 'sup4',
 'sup4_xl_bo2_rm4_6b',
 'sup4_ppo_rm3_kl20',
 'sup4_ppo_rm3_kl69',
 'sup4_xl_bo2_rm4',
 'sup4_ppo_rm3_kl9',
 'sup3',
 'sup4_6b_t0.7',
 'ref',
 'sup4_xl_bo64_rm4_6b',
 'sup4_xl_bo1024_rm4_6b',
 'sup2_bo8_rm1',
 'sup4_xl_bo2_rouge',
 'sup4_xl_bo1024_rouge',
 'sup2',
 'sup1',
 'sup4_t0.7',
 'sup4_xl_bo8_rouge',
 'sup4_bo256_rm3',
 'sup4_6b_p.7',
 'sup4_xl_bo2_rm3',
 'sup4_6b_p.8',
 'sup4_3b_t0.7',
 'sup3_ppo_rm1',
 'sup4_bo8_rm3',
 'sup4_xl_bo16_rouge',
 'sup4_xl_bo16_rm3',
 'sup4_6b_p.95',
 'sup4_ppo_rm3_kl260',
 'sup4_xl_bo16_rm4_6b',
 'sup4_xl_bo1024_rm3',
 'sup4_xl_bo512_rm4_6b',
 'sup4_xl_bo8_rm4_6b',
 'pretrain_xl_t.7',
 'title',
 'sup4_ppo_rm4_t.7',
 'sup4_bo512_rm3',
 'sup4_xl_bo128_rouge',
 'sup4_xl_bo512_rm4',
 'sup4_12b',
 'pretrain_6b']

In [53]:
policies[np.argmax(strength)]

'sup4_6b_ppo_rm4_6b_t.5'

In [52]:
[x for _, x in sorted(zip(strength, policies),reverse=True)]

['sup4_6b_ppo_rm4_6b_t.5',
 'sup4_6b_ppo_rm4_6b',
 'sup4_6b_ppo_rm4_6b_t.7',
 'sup4_6b_ppo_rm4_6b_kl14',
 'sup4_xl_bo1024_rm4_6b',
 'sup4_xl_bo1024_rm4',
 'sup4_ppo_rm4',
 'sup4_xl_bo128_rm4_6b',
 'sup4_xl_bo64_rm4_6b',
 'sup4_6b_ppo_rm3_6b_kl15',
 'sup4_xl_bo512_rm4_6b',
 'sup4_xl_bo512_rm4',
 'sup3_bo63_rm2',
 'sup4_bo256_rm3_6b',
 'sup4_xl_bo16_rm4_6b',
 'sup4_bo128_rm3_6b',
 'sup4_ppo_rm4_t.7',
 'sup4_bo256_rm3',
 'sup4_xl_bo128_rm4',
 'sup4_xl_bo1024_rm3',
 'ref',
 'sup4_bo128_rm3',
 'sup4_bo64_rm3',
 'sup4_ppo_rm3_kl22',
 'sup4_xl_bo64_rm4',
 'sup3_bo8_rm2',
 'sup4_ppo_rm3_kl9',
 'sup4_ppo_rm3_kl10',
 'sup4_12b',
 'sup4_xl_bo8_rm4_6b',
 'sup4_bo512_rm3',
 'sup4_ppo_rm3_kl69',
 'sup4_ppo_rm3_kl6',
 'sup4_xl_bo16_rm3',
 'sup4_6b',
 'sup4_xl_bo8_rm4',
 'sup4_6b_t.3',
 'sup2_bo8_rm1',
 'sup4_ppo_rm3_kl20',
 'sup4_ppo_rm3',
 'sup4_3b',
 'sup4',
 'sup4_ppo_rm3_kl2',
 'sup4_6b_t.5',
 'sup4_bo8_rm3',
 'sup3_6b',
 'sup3_ppo_rm1',
 'sup4_xl_bo16_rm4',
 'pretrain_3b',
 'pretrain_12b',
 'sup