In [2]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import time

# import the two classes containing the algorithms
import scaling
import inference

In [3]:
# generate ranking data from SUSHI-10 dataset
# note that in the data the first column denotes the number of times
# such rankings are recorded

data = np.loadtxt('sushi.txt',delimiter = ',')
data = data.astype(int)
nb_items = 10
rankings = ()
num_rankings = np.sum(data[:,0])
for i in range(data.shape[0]):
    for j in range(int(data[i,0])):
        ranking = tuple(data[i,1:]-1)
        rankings = rankings + (ranking,)

In [4]:
data

array([[ 3,  7,  4, ...,  3,  9,  6],
       [ 3,  4,  5, ...,  1,  6,  9],
       [ 3,  4,  5, ...,  8,  6,  9],
       ...,
       [ 1, 10,  3, ...,  1,  7,  4],
       [ 1,  5,  6, ...,  9, 10,  3],
       [ 1,  2, 10, ...,  7,  5,  4]])

In [50]:
num_rankings

5000

In [7]:
# generate comparison matrix and winning count
A, p = scaling.ranking_to_choice(nb_items,rankings)

# MLE with scaling algorithm
start = time.time()
scaling_strength, scaled_A, iterations = scaling.iterative_scaling(A,p)
end = time.time()
print('Scaling algorithm converged in ',iterations, 'iterations and took ',end-start,'seconds.')

# MLE with iterative LSR algorithm
start = time.time()
ilsr_strength, iterations = inference.ilsr(nb_items,rankings)
end = time.time()
print('Iterative LSR algorithm converged in ',iterations, 'iterations and took ',end-start,'seconds.')

Scaling algorithm converged in  16 iterations and took  0.025513887405395508 seconds.
Iterative LSR algorithm converged in  8 iterations and took  1.7084746360778809 seconds.


In [52]:
(m,n) = scaled_A.shape
uniform = np.ones(m)/m
np.dot(scaled_A.T,uniform)-p

array([ 4.16333634e-16,  5.55111512e-17,  4.71844785e-16,  5.68989300e-16,
        6.93889390e-17, -1.11022302e-16,  2.08166817e-16,  6.93889390e-17,
        3.12250226e-15, -1.92901251e-15])

In [53]:
np.sum(scaled_A,axis=1)

array([1., 1., 1., ..., 1., 1., 1.])

In [54]:
scaling_strength/scaling_strength.sum()

array([0.09145086, 0.14217679, 0.07710968, 0.06844782, 0.0939343 ,
       0.0509258 , 0.24495368, 0.0858835 , 0.03418853, 0.11092903])

In [55]:
ilsr_strength/ilsr_strength.sum()

array([0.09145086, 0.14217679, 0.07710968, 0.06844782, 0.0939343 ,
       0.0509258 , 0.24495368, 0.0858835 , 0.03418853, 0.11092903])

In [56]:
scaling_strength/scaling_strength.sum() - ilsr_strength/ilsr_strength.sum()

array([ 1.46329310e-10, -9.73536807e-11,  1.28157970e-10,  1.00436021e-10,
        9.44645334e-11,  1.24134994e-10, -7.72017672e-10,  7.36832817e-11,
        7.79478149e-11,  1.24217539e-10])