In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('gifgif-dataset-20150121-v1.csv')

In [3]:
data

metric            left           right   choice
0             pleasure  12f31lpt5QGIWQ   l6P0GVe4S3mAE     left
1              disgust   DyNkr3cZgBWCI   QEclThAw6HjBS  neither
2              disgust   6MhFm3LXoVQn6  12qogXnmccuga4    right
3            happiness   4YGHghupBy2Aw   2SC7Ue2B9OdRm  neither
4            happiness   tGWGdTIwnLOw0   W3hdeQrGv6mqs    right
5                pride   V0IvQncc1Ut9e  12eHTgKMw6Ocgw  neither
6             pleasure  12BVra7wmax12E   2Wv76xVF415S0    right
7             pleasure   j4LLz8zhCXQoU   s9ndWpnpML4KA     left
8           excitement   RclRc1LK6niU0   mzyZMTBJSKnzq     left
9            happiness   rsBVkMZABjup2  132ZLaGcyQrUoE  neither
10       embarrassment   6rBc4u6R8sN32   rZSbXMHGq61cA     left
11            surprise  11KgddPnJzcipW   NUVK9yTjYVGBa     left
12             sadness   AyJ1zHGG7g4dq   8mN9zChg5KbE4  neither
13            pleasure   TrSqUougSkFO0   TVguaCSDWPTLq     left
14                fear   2QpH5Khv9ooec   BcVzio5hKnY3e    right
15                fear   UolmMP8IZhrlS   WoYwgrfZP4yw8  neither
16       embarrassment   7pvxsElPIkqHK   gjX5FKaQf0pMc  neither
17        satisfaction   dvlWMtltmqaxG   yK5FrRpv6fsUU  neither
18               guilt   rfk84JOt3jc3u   zlNfhZYMEpdaE  neither
19             disgust   nQF1cq3tEs8h2   4fXsOab5IxuUw    right
20        satisfaction   jeXiz1RAvzX44   Bo0F2pW8jgTPq    right
21             sadness   u5yfQebO9VkXu   qi5bVdSALGMWk  neither
22             sadness   mzTKsByk8Xl6g   IeLOBZb7ZdQ1G  neither
23             disgust   lKB8UY8I6u5kA   JYYfOAOG2bICk  neither
24       embarrassment   d34YuFVFieH4c   ndcigCKnYLYWs  neither
25             disgust   ufb7kYdOArVzW   g2L4WvIB1JLfq  neither
26               pride   7fhsSdSzswOfS   5bm9GcwO2nHG0  neither
27            contempt  13dNZ2V71MJtbG   bQ4qx1qT28rHG  neither
28                fear   R1CJ00kQSO0fe   Pr32hXmrWE0Ny  neither
29               shame   nYiPMOjFWqygE   aqf59k9FVolMs  neither
...                ...             ...             ...      ...
2736204  embarrassment   ZRwJd1fi2Mysg   s1lUtvqPhAXPG    right
2736205         relief   Blj0nykpHjmrC   TxUPfG8fxcaNG  neither
2736206          anger   9mcduSBrmMgkE   vFjCSVR9MhUgE     left
2736207        disgust   ZZF4Tlfvn7Bo4   5SOcQgsBcqDW8     left
2736208       surprise   OqILpEsb0DNfO   Z62W9AyfVWKwE  neither
2736209        disgust   zVuwUlDNKTCFO   tydszM0eQDJNC  neither
2736210          anger   eU9lAuONvjFQc  11BYCaPUORN0ZO  neither
2736211          shame   p8BOVqc17KVy0   9YKHJycHTSZ2M  neither
2736212  embarrassment   eHGqM3GLMQjG8   qcinxx6aYutRC     left
2736213          guilt   3NUJ4FwSp4MJG   uwNSb7AFF9b8Y  neither
2736214       pleasure   bzUuWKaGESiaY   nXOds9I8K8gUg  neither
2736215       surprise   O2ywa6Mq97n6o   Ry4eUUKGyz0vS  neither
2736216    contentment   SK0sLeQEPSl4Q   2ADJrKQnqtZhm  neither
2736217        disgust   2bXkC5JOPFoGc    YrSlt0NJshH2    right
2736218     excitement  11gEjkL5Fhztks   84xixy5mVrGJW  neither
2736219          anger   I4fvDjTDt7OWQ   BYLdx1PdIe8ow     left
2736220      happiness   mASU0YHKYM372   2sQq0J0ZiadO0  neither
2736221       surprise   TrSqUougSkFO0   qcnmXmEYdLTKE  neither
2736222           fear   L2Gkc6WuxpgvS  10IWifjzu0nOXC  neither
2736223          anger   93uYptVAHE7C0   fXi1GVdexuliM  neither
2736224       surprise   dnbFBwyKULVKM   Kf6lPySyD0ggM  neither
2736225    contentment   EPsdF1SvWrzHy   fIQYb3QwojT7a  neither
2736226       contempt   MeBouHhjOTyjm   8kuLlSpafifuw    right
2736227        disgust   czZxIdTSm6QTK   UblfC3q1UEaYM    right
2736228      amusement   dT3JRzKw57fji   PJvv1eQvRnbFK    right
2736229   satisfaction   I5oD4haWuUnUQ    ZJoCfb9ZMg5q  neither
2736230           fear   oktRrJuhxCZSU   Ti3i7TumKRkdi  neither
2736231          shame   2KEQJjChy7JXW  14kG3TRz1uzWOk  neither
2736232          guilt   Y4z9olnoVl5QI   X1Ga5a4wVW396     left
2736233      amusement  11BUSuy66XlKDe   spdOikRDot14c  neither

[2736234 rows x 4 columns]

In [4]:
data = data[data['choice'].isin(['left','right'])]
data

metric            left           right choice
0             pleasure  12f31lpt5QGIWQ   l6P0GVe4S3mAE   left
2              disgust   6MhFm3LXoVQn6  12qogXnmccuga4  right
4            happiness   tGWGdTIwnLOw0   W3hdeQrGv6mqs  right
6             pleasure  12BVra7wmax12E   2Wv76xVF415S0  right
7             pleasure   j4LLz8zhCXQoU   s9ndWpnpML4KA   left
8           excitement   RclRc1LK6niU0   mzyZMTBJSKnzq   left
10       embarrassment   6rBc4u6R8sN32   rZSbXMHGq61cA   left
11            surprise  11KgddPnJzcipW   NUVK9yTjYVGBa   left
13            pleasure   TrSqUougSkFO0   TVguaCSDWPTLq   left
14                fear   2QpH5Khv9ooec   BcVzio5hKnY3e  right
19             disgust   nQF1cq3tEs8h2   4fXsOab5IxuUw  right
20        satisfaction   jeXiz1RAvzX44   Bo0F2pW8jgTPq  right
30               pride   h5YJdPfkSbcRO   PSltNqE9JPmPS   left
31            surprise   Kmvw4jeFNPWEg   BPXMRr73PQ9Xy  right
34          excitement   3puJvSfpIc9fW   RCk0yprDHSjhS  right
38               anger   ThIpoXTtlnfHy   BaGUxEtYBFYGs  right
40            contempt   5XFRzDJlcQWMU   pcS0TevQPqixq  right
41          excitement   d1tlu8P8b5FkY   i7gcqHL0Fb9mg  right
43             disgust   E6fZ47O87uC7S   ZnXQD1ycwxDRm  right
44            surprise   rvasIXgTtFkze   MP5QpDGwSr1mw   left
46           happiness   YH7fjh6VFRpEA   pQaIuyRbf0lsk  right
49            pleasure   EWhLjxjiqdZjW   KZvT5AWF4ADAI   left
52            contempt   EPDYxZH7072QU   g6SZGHtNmC9t6  right
53               pride   7U1XfwZ94okRW   qw4NFPVCEoUXm  right
56               pride   7HQExY9eErOcE   ReltxRUhwdm2Q  right
58           amusement   p1iiaffStZOs8  10VFOe0kP0HamY   left
59         contentment   J0UgtZkOjXOeY   7SQtrK5JbFTFK  right
63          excitement   aB8acJ0dByuGY   iCh8iLOteYr0Q  right
69              relief   tDedxgNbW4Qo0   ds8khI25lsR3y   left
71               pride   qycEOCsO6eP28   2XDUKw5TUUWJi  right
...                ...             ...             ...    ...
2736144     excitement   R3JNnwozrp99C   ci9L7WOiFjuyk  right
2736146        sadness   zfLgghO7G1n7W   6DUuofMZuKiGY   left
2736148          guilt   y2giNwzUHN1p6   T5qkXkas94u4w  right
2736149        disgust   X1z9aO8QWpdio   6sjfJk4cz9ei4  right
2736150       surprise   9uCiMuCg2ESEo   eS3SzyemxxE2s  right
2736151         relief   psKReJOWm4cfK  12Q3i3cxuyj2ow  right
2736152        disgust   fdHg7T902uzLy   tlpw4QGG8aJsk   left
2736153       contempt   Ckf5d48lO8iac   omKrSxEuxGyRy   left
2736164         relief   NoglyWTK9tCMw   NbuSl5HBXg7JK  right
2736165      happiness  11gEjkL5Fhztks   qquibhXs9pEIM   left
2736168      amusement   jkQ4Ys599gbzG   3sLiXWTj8WXNC  right
2736170         relief  118zgIxNQvQpcA   4mmH5IrQ0Jnwc   left
2736179       pleasure   kyjkfrL7W8OmA   zcBT4vLa7JbfG  right
2736180      amusement   cRjg3vUuEP3dC   mBK3T1nZAP1jq   left
2736184       pleasure  12PIT4DOj6Tgek   WW8RegnHLmwIU   left
2736193       surprise   rfWAomOTPeOo8  12r1CuyUyFojFS   left
2736195       surprise  140QrhwMTVUyeA   F182HCX5excbK   left
2736196   satisfaction   EL3n3gV04pCfe   HtYsYjPsw1nVu  right
2736197     excitement   Kcpv9ZnHvWyac   isY0HE006jGDu  right
2736200    contentment   lmQ4771HAEc1O   l04QF7eek5iGQ  right
2736204  embarrassment   ZRwJd1fi2Mysg   s1lUtvqPhAXPG  right
2736206          anger   9mcduSBrmMgkE   vFjCSVR9MhUgE   left
2736207        disgust   ZZF4Tlfvn7Bo4   5SOcQgsBcqDW8   left
2736212  embarrassment   eHGqM3GLMQjG8   qcinxx6aYutRC   left
2736217        disgust   2bXkC5JOPFoGc    YrSlt0NJshH2  right
2736219          anger   I4fvDjTDt7OWQ   BYLdx1PdIe8ow   left
2736226       contempt   MeBouHhjOTyjm   8kuLlSpafifuw  right
2736227        disgust   czZxIdTSm6QTK   UblfC3q1UEaYM  right
2736228      amusement   dT3JRzKw57fji   PJvv1eQvRnbFK  right
2736232          guilt   Y4z9olnoVl5QI   X1Ga5a4wVW396   left

[1094988 rows x 4 columns]

In [5]:
data = data[data['metric'].isin(['happiness',])]
data

metric            left           right choice
4        happiness   tGWGdTIwnLOw0   W3hdeQrGv6mqs  right
46       happiness   YH7fjh6VFRpEA   pQaIuyRbf0lsk  right
74       happiness   HMbnnGytujuqk   nlbIlT8dEZ0as   left
137      happiness   tRIrEPn9FIsSI   Rlo6lDGkmddug   left
141      happiness   vbI0U3D7Pl2RW    zvgtQjrsDn32   left
160      happiness   32mMKTt7izPhK   TPI9G36RtHIPu   left
184      happiness   jK872cYkccms0   pIWlSGZ4fkMlq  right
215      happiness   qnkztOGd3vh6M   Y8MgD1J63Eeo8  right
224      happiness  11W2KbIu2lBJkc   ze57I4PUHVPzi   left
236      happiness   3pBnLxw0TMwRW   47Uw4wCQ9ft1S   left
250      happiness   aU4jau5ql99EA   yY3q1MnRCBHoI   left
255      happiness   4NeDNHUQne288  125V825B3Q0TXW   left
265      happiness   GpFkiAUrnTUME   ztWHpHzojfzDa  right
277      happiness   9x7gvqaWEG7qE   HIbAnvs9DwnfO  right
287      happiness   wkwDk316O9kEE   fUE1L1Dd7P0v6  right
296      happiness   uDljXVi1w6Xmg  11SQyf0LLqaGSk  right
348      happiness   9fkruVI9QO8s8   8t4NEufUnZJFm  right
374      happiness   S4hb1QPb19NkY   nuGsEYoyhYgAo   left
471      happiness   bQ4qx1qT28rHG   obfsjkhZHeYlq  right
526      happiness   uGZovkJVmarXq   vTd0nAsdsb24U   left
540      happiness   eN2cIZkymBHk4   dkGhBWE3SyzXW  right
567      happiness   ntQmplXABw2Na   yWs708JtjQXRe   left
580      happiness   Ye2f285pw8tzO   YEQSj6RESe0s8   left
641      happiness   5WjgnOQEy0a76   QEKSVyUUcJOww  right
650      happiness   wzGx51aKRSxUc   DRnfgADjQuYKY  right
680      happiness   NlpnSfpBdjwxG   L2UdIWuCRbUL6  right
709      happiness   WakVeAOiSzp4s   7mxD8M9juTC9O   left
713      happiness   7I8KIUtCiW4xy   KMq0HIWYrnAD6  right
721      happiness   brsEO1JayBVja   ORwxEDQCjBb4k  right
724      happiness   sOmRAygZkfRRK    E9EN2Ql6NjXO  right
...            ...             ...             ...    ...
2735531  happiness  10DEIsgAnAESVW   5NVx4j42L3Ghy   left
2735537  happiness   HmsAidDdKMTle   sJGL3KE7DpbcA   left
2735540  happiness   yPqRjsnnbWOac   bCBFCAa4ZMzh6   left
2735562  happiness   gj8bDcA9gKi5i   blzvaEmaIJ8KA  right
2735607  happiness   4Ra6jnDDOVdNS   5khmPdwkHZxIc   left
2735667  happiness   IvY2Fs6BL4dWg   brHaCdJqCXijm  right
2735676  happiness   nkBa9eREC4D7O   4o9dErIzREOxa   left
2735696  happiness  12WVH5eiudcf6w   foYSObiYEshUc  right
2735719  happiness   jwa7CacCFni6I   HOPkTmfmnQuQw  right
2735762  happiness   tlKTIYel9FlTO   K7vCPqBpD9cas   left
2735802  happiness   DMVNskCf4Phmw   XAvDiScbUMhxu  right
2735816  happiness    cct4cxIIxJ3q   BJx5OqnGDiPZe   left
2735834  happiness   7SQtrK5JbFTFK  108vlcPflbDDOM   left
2735841  happiness   amIt8Jyb9V9Pq   ZUvgoToZBf74Q  right
2735853  happiness   jeXiz1RAvzX44   9uxyR5C8T6KBi  right
2735870  happiness   I5zqiSHDo9HC8   VzgIAezXGwcwg   left
2735875  happiness   iiQoy4Y8bueVW   MOthMq819y8es   left
2735910  happiness   1rUm8QKEpeOn6   DnXX71x8GnYPe   left
2735913  happiness   DcYsE57PYPrHy   R2IptHMaSuQXS   left
2735914  happiness  12Q3i3cxuyj2ow   O3WTf9CpJ8LjW   left
2735917  happiness   1vTg1SPYlciDm   jECkHqRbNKuNG  right
2735946  happiness   xNYbjhQPCZOaQ   hfZ9oWRkkZ9YY   left
2735947  happiness   lLQKng4l4oPm0   46NpwxfrMAOD6   left
2736027  happiness   rdJALMHoIvkWs   U6JR05at2HHhe   left
2736059  happiness   BCSXLnFSTQ3h6   BCOZjy2WLe8FO   left
2736067  happiness   yY3q1MnRCBHoI   iiQoy4Y8bueVW  right
2736081  happiness   2lr4nJQaqWc7e   OqILpEsb0DNfO  right
2736094  happiness   eEJSYaSjkgasM   RgPrV63CYg2Ig   left
2736106  happiness   qWqo8GZJJoxUY  12WcpB0Kms9rGM   left
2736165  happiness  11gEjkL5Fhztks   qquibhXs9pEIM   left

[106887 rows x 4 columns]

In [7]:
idx = data['choice'] =='right'
data.loc[idx,['left','right']] = data.loc[idx,['right','left']].values
data = data.drop(columns=['metric','choice'])
data

c:\users\zhaon\appdata\local\programs\python\python36\lib\site-packages\pandas\core\indexing.py:194: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)
c:\users\zhaon\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


left           right
4         W3hdeQrGv6mqs   tGWGdTIwnLOw0
46        pQaIuyRbf0lsk   YH7fjh6VFRpEA
74        HMbnnGytujuqk   nlbIlT8dEZ0as
137       tRIrEPn9FIsSI   Rlo6lDGkmddug
141       vbI0U3D7Pl2RW    zvgtQjrsDn32
160       32mMKTt7izPhK   TPI9G36RtHIPu
184       pIWlSGZ4fkMlq   jK872cYkccms0
215       Y8MgD1J63Eeo8   qnkztOGd3vh6M
224      11W2KbIu2lBJkc   ze57I4PUHVPzi
236       3pBnLxw0TMwRW   47Uw4wCQ9ft1S
250       aU4jau5ql99EA   yY3q1MnRCBHoI
255       4NeDNHUQne288  125V825B3Q0TXW
265       ztWHpHzojfzDa   GpFkiAUrnTUME
277       HIbAnvs9DwnfO   9x7gvqaWEG7qE
287       fUE1L1Dd7P0v6   wkwDk316O9kEE
296      11SQyf0LLqaGSk   uDljXVi1w6Xmg
348       8t4NEufUnZJFm   9fkruVI9QO8s8
374       S4hb1QPb19NkY   nuGsEYoyhYgAo
471       obfsjkhZHeYlq   bQ4qx1qT28rHG
526       uGZovkJVmarXq   vTd0nAsdsb24U
540       dkGhBWE3SyzXW   eN2cIZkymBHk4
567       ntQmplXABw2Na   yWs708JtjQXRe
580       Ye2f285pw8tzO   YEQSj6RESe0s8
641       QEKSVyUUcJOww   5WjgnOQEy0a76
650       DRnfgADjQuYKY   wzGx51aKRSxUc
680       L2UdIWuCRbUL6   NlpnSfpBdjwxG
709       WakVeAOiSzp4s   7mxD8M9juTC9O
713       KMq0HIWYrnAD6   7I8KIUtCiW4xy
721       ORwxEDQCjBb4k   brsEO1JayBVja
724        E9EN2Ql6NjXO   sOmRAygZkfRRK
...                 ...             ...
2735531  10DEIsgAnAESVW   5NVx4j42L3Ghy
2735537   HmsAidDdKMTle   sJGL3KE7DpbcA
2735540   yPqRjsnnbWOac   bCBFCAa4ZMzh6
2735562   blzvaEmaIJ8KA   gj8bDcA9gKi5i
2735607   4Ra6jnDDOVdNS   5khmPdwkHZxIc
2735667   brHaCdJqCXijm   IvY2Fs6BL4dWg
2735676   nkBa9eREC4D7O   4o9dErIzREOxa
2735696   foYSObiYEshUc  12WVH5eiudcf6w
2735719   HOPkTmfmnQuQw   jwa7CacCFni6I
2735762   tlKTIYel9FlTO   K7vCPqBpD9cas
2735802   XAvDiScbUMhxu   DMVNskCf4Phmw
2735816    cct4cxIIxJ3q   BJx5OqnGDiPZe
2735834   7SQtrK5JbFTFK  108vlcPflbDDOM
2735841   ZUvgoToZBf74Q   amIt8Jyb9V9Pq
2735853   9uxyR5C8T6KBi   jeXiz1RAvzX44
2735870   I5zqiSHDo9HC8   VzgIAezXGwcwg
2735875   iiQoy4Y8bueVW   MOthMq819y8es
2735910   1rUm8QKEpeOn6   DnXX71x8GnYPe
2735913   DcYsE57PYPrHy   R2IptHMaSuQXS
2735914  12Q3i3cxuyj2ow   O3WTf9CpJ8LjW
2735917   jECkHqRbNKuNG   1vTg1SPYlciDm
2735946   xNYbjhQPCZOaQ   hfZ9oWRkkZ9YY
2735947   lLQKng4l4oPm0   46NpwxfrMAOD6
2736027   rdJALMHoIvkWs   U6JR05at2HHhe
2736059   BCSXLnFSTQ3h6   BCOZjy2WLe8FO
2736067   iiQoy4Y8bueVW   yY3q1MnRCBHoI
2736081   OqILpEsb0DNfO   2lr4nJQaqWc7e
2736094   eEJSYaSjkgasM   RgPrV63CYg2Ig
2736106   qWqo8GZJJoxUY  12WcpB0Kms9rGM
2736165  11gEjkL5Fhztks   qquibhXs9pEIM

[106887 rows x 2 columns]

In [17]:
s0 = pd.Series(data['left'])
s1 = pd.Series(data['right'])
stacked = pd.concat([s0,s1])
catify = stacked.astype('category')

In [18]:
catify

4           W3hdeQrGv6mqs
46          pQaIuyRbf0lsk
74          HMbnnGytujuqk
137         tRIrEPn9FIsSI
141         vbI0U3D7Pl2RW
160         32mMKTt7izPhK
184         pIWlSGZ4fkMlq
215         Y8MgD1J63Eeo8
224        11W2KbIu2lBJkc
236         3pBnLxw0TMwRW
250         aU4jau5ql99EA
255         4NeDNHUQne288
265         ztWHpHzojfzDa
277         HIbAnvs9DwnfO
287         fUE1L1Dd7P0v6
296        11SQyf0LLqaGSk
348         8t4NEufUnZJFm
374         S4hb1QPb19NkY
471         obfsjkhZHeYlq
526         uGZovkJVmarXq
540         dkGhBWE3SyzXW
567         ntQmplXABw2Na
580         Ye2f285pw8tzO
641         QEKSVyUUcJOww
650         DRnfgADjQuYKY
680         L2UdIWuCRbUL6
709         WakVeAOiSzp4s
713         KMq0HIWYrnAD6
721         ORwxEDQCjBb4k
724          E9EN2Ql6NjXO
                ...      
2735531     5NVx4j42L3Ghy
2735537     sJGL3KE7DpbcA
2735540     bCBFCAa4ZMzh6
2735562     gj8bDcA9gKi5i
2735607     5khmPdwkHZxIc
2735667     IvY2Fs6BL4dWg
2735676     4o9dErIzREOxa
2735696    1

In [19]:
code = catify.cat.codes

In [20]:
code

4          3626
46         5210
74         2306
137        5578
141        5749
160         794
184        5198
215        3766
224         189
236         896
250        3970
255         958
265        6106
277        2302
287        4427
296         179
348        1479
374        3302
471        5147
526        5651
540        4286
567        5089
580        3812
641        3151
650        1981
680        2627
709        3654
713        2558
721        2966
724        2038
           ... 
2735531    1077
2735537    5469
2735540    4051
2735562    4529
2735607    1117
2735667    2440
2735676    1017
2735696     318
2735719    4788
2735762    2537
2735802    1968
2735816    1757
2735834      24
2735841    4009
2735853    4757
2735870    3616
2735875    2750
2735910    2019
2735913    3219
2735914    2929
2735917     681
2735946    4602
2735947     920
2736027    3469
2736059    1742
2736067    6006
2736081     768
2736094    3267
2736106     320
2736165    5339
Length: 213774, dtype: i

In [21]:
matrix = np.zeros((106887,2))

In [22]:
matrix[:,0] = code.iloc[0:106887]

In [23]:
matrix[:,1] = code.iloc[106887:]

In [24]:
matrix.min()

-1.0

In [25]:
matrix.max()

6118.0

In [26]:
matrix

array([[3626., 5562.],
       [5210., 3780.],
       [2306., 5081.],
       ...,
       [4316., 3267.],
       [5305.,  320.],
       [ 202., 5339.]])

In [27]:
matrix.shape

(106887, 2)

In [29]:
#We have obtained comparisons in the form of IDs starting from -1 up to 6118.
#Now convert this to tuples of rankings. 

In [32]:
matrix = matrix.astype(int)
np.savetxt('gifgif_raw.txt',matrix,delimiter=',',fmt='%d')

In [31]:
# below is scrach, may continue to the MLE notebook

In [20]:
matrix = matrix[:50000,:]

In [21]:
import networkx as nx

In [22]:
matrix.shape

(50000, 2)

In [23]:
G = nx.DiGraph()

In [24]:
#build ranking data, need to select largest strongly connected component
rankings = list(map(tuple, matrix))

In [25]:
rankings

[(18681, 19936),
 (18681, 20564),
 (14414, 18681),
 (18681, 10924),
 (18681, 13680),
 (14414, 19994),
 (14414, 8230),
 (1313, 6214),
 (19721, 20164),
 (18681, 1084),
 (14414, 18690),
 (14414, 60),
 (14414, 4999),
 (18681, 9724),
 (18681, 18430),
 (12905, 19721),
 (14414, 12544),
 (12905, 10226),
 (15789, 13130),
 (7633, 9262),
 (14414, 20178),
 (12905, 3986),
 (7633, 14612),
 (7633, 14414),
 (7633, 14414),
 (12905, 7633),
 (12905, 10442),
 (17763, 14584),
 (17763, 6975),
 (17763, 4248),
 (15998, 18789),
 (17763, 20031),
 (12597, 17763),
 (15998, 11736),
 (17469, 17763),
 (12597, 10),
 (12597, 13742),
 (1938, 20826),
 (12597, 13083),
 (12597, 17469),
 (7168, 17469),
 (17469, 17708),
 (1938, 15628),
 (3788, 6110),
 (12597, 10578),
 (7168, 10578),
 (15998, 11424),
 (15998, 13590),
 (7168, 5277),
 (8219, 1369),
 (12597, 7168),
 (15998, 1414),
 (15998, 1414),
 (15998, 13794),
 (15998, 999),
 (17013, 1094),
 (8219, 8976),
 (1938, 15467),
 (1938, 18141),
 (12597, 15998),
 (12597, 15998),
 (15

In [26]:
G.add_edges_from(rankings)

In [27]:
G = max(nx.strongly_connected_component_subgraphs(G), key=len)

In [28]:
Adjacency = nx.adjacency_matrix(G)

In [29]:
Adjacency = Adjacency.toarray()

In [30]:
p = np.sum(Adjacency,1)

In [31]:
n = np.sum(Adjacency)

In [32]:
m = Adjacency.shape[0]

In [33]:
A = np.zeros((n,m))

In [34]:
#np.squeeze((Adjacency[1,:]==1).toarray())

In [35]:
index = 0
for i in range(m):
    length = np.sum(Adjacency[i,:])
    pair = np.where(Adjacency[i,:]==1)[0]
    A[index:index+length,i] = 1
    A[np.arange(index,index+length),pair] = 1
    index += length
    print(A)

[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ...

[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ...

[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ...

[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ...

[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ...

[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ...

[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ...

[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ...

[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ...

[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ...

 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ..

[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ...

[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ...

[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ...

 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ..

[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ...

 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ..

 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ..

[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ...

[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ...

 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ..

[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ...

 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ..

 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ..

[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ...

In [37]:
sum(A[:,1])

25.0

In [38]:
A

array([[1., 1., 0., ..., 0., 0., 0.],
       [1., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [40]:
sum(Adjacency[1,:])

15

In [41]:
Adjacency

array([[0, 1, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)

In [44]:
list(G.edges())

[(18681, 19936),
 (18681, 20564),
 (18681, 10924),
 (18681, 13680),
 (18681, 1084),
 (18681, 9724),
 (18681, 18430),
 (18681, 1782),
 (18681, 13806),
 (18681, 5829),
 (18681, 18671),
 (18681, 13462),
 (18681, 391),
 (18681, 3687),
 (18681, 6812),
 (18681, 14072),
 (18681, 12499),
 (18681, 6549),
 (18681, 6403),
 (18681, 20695),
 (18681, 13063),
 (18681, 16224),
 (18681, 17312),
 (18681, 15203),
 (18681, 11058),
 (18681, 10974),
 (18681, 12047),
 (18681, 15068),
 (18681, 15655),
 (18681, 14686),
 (18681, 17922),
 (18681, 7068),
 (18681, 15322),
 (18681, 5166),
 (18681, 14102),
 (18681, 7972),
 (18681, 12246),
 (18681, 5584),
 (18681, 17374),
 (18681, 15974),
 (18681, 18327),
 (19936, 20298),
 (19936, 4485),
 (19936, 7673),
 (19936, 5929),
 (19936, 5573),
 (19936, 687),
 (19936, 13421),
 (19936, 16676),
 (19936, 17608),
 (19936, 1251),
 (19936, 9603),
 (19936, 1874),
 (19936, 8456),
 (19936, 918),
 (19936, 1901),
 (20564, 7004),
 (20564, 19492),
 (20564, 10659),
 (20564, 9131),
 (20564, 