In [5]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import time

# import the two classes containing the algorithms
import scaling
import inference

In [9]:
# generate ranking data from SUSHI-100 dataset
# note that in the data the first column denotes the number of times
# such rankings are recorded

data = np.loadtxt('sushi_large.txt')
data = data.astype(int)
nb_items = 100
rankings = ()
num_rankings = np.sum(data[:,0])
for i in range(data.shape[0]):
    for j in range(int(data[i,0])):
        ranking = tuple(data[i,1:]-1)
        rankings = rankings + (ranking,)

In [10]:
data

array([[ 1, 58,  4, ...,  1, 12, 74],
       [ 1, 22, 31, ..., 12, 17, 76],
       [ 1,  2, 15, ..., 74, 56, 55],
       ...,
       [ 1, 19, 14, ..., 46, 60, 30],
       [ 1, 37,  2, ..., 48,  4, 64],
       [ 1,  9,  3, ..., 23, 42, 25]])

In [11]:
num_rankings

5000

In [23]:
# generate comparison matrix and winning count
A, p = scaling.ranking_to_choice(nb_items,rankings)

# MLE with scaling algorithm
start = time.time()
scaling_strength, scaled_A, iterations = scaling.iterative_scaling(A,p)
end = time.time()
print('Scaling algorithm converged in ',iterations, 'iterations and took ',end-start,'seconds.')

# MLE with iterative LSR algorithm
start = time.time()
ilsr_strength, iterations = inference.ilsr(nb_items,rankings)
end = time.time()
print('Iterative LSR algorithm converged in ',iterations, 'iterations and took ',end-start,'seconds.')

Scaling algorithm converged in  21 iterations and took  0.25332045555114746 seconds.
Iterative LSR algorithm converged in  9 iterations and took  2.142876148223877 seconds.


In [24]:
(m,n) = scaled_A.shape
uniform = np.ones(m)/m
np.dot(scaled_A.T,uniform)-p

array([-6.24500451e-17, -3.46944695e-18,  7.28583860e-17, -6.93889390e-18,
       -7.63278329e-17,  1.07552856e-16, -1.73472348e-17, -7.97972799e-17,
        8.67361738e-17, -1.38777878e-17,  2.42861287e-17, -3.46944695e-18,
       -6.93889390e-18, -2.42861287e-17, -2.08166817e-17,  3.46944695e-18,
       -2.77555756e-17, -4.16333634e-17,  2.42861287e-17,  1.04083409e-17,
        6.93889390e-18,  1.04083409e-17, -1.04083409e-17, -2.77555756e-17,
       -5.20417043e-17,  3.46944695e-18,  2.08166817e-17,  1.56125113e-17,
        3.46944695e-18, -1.38777878e-17,  1.38777878e-17, -8.67361738e-18,
        3.29597460e-17, -2.77555756e-17,  6.93889390e-18,  1.73472348e-18,
        2.25514052e-17,  1.38777878e-17, -1.56125113e-17, -8.67361738e-18,
        1.73472348e-17, -3.46944695e-18,  0.00000000e+00,  4.33680869e-18,
        5.20417043e-18,  4.33680869e-18,  0.00000000e+00, -8.67361738e-18,
       -6.93889390e-18,  3.38271078e-17,  1.73472348e-18,  0.00000000e+00,
       -2.60208521e-18, -

In [25]:
np.sum(scaled_A,axis=1)

array([1., 1., 1., ..., 1., 1., 1.])

In [26]:
scaling_strength/scaling_strength.sum()

array([0.01595761, 0.02465364, 0.01435528, 0.01018711, 0.01160215,
       0.01538562, 0.00909814, 0.0342776 , 0.02266499, 0.01594566,
       0.02033338, 0.00792053, 0.01692455, 0.01073288, 0.02099381,
       0.00675822, 0.00511985, 0.00812189, 0.03657007, 0.0183859 ,
       0.01398052, 0.01711026, 0.00718943, 0.00667292, 0.01158058,
       0.01615035, 0.01473765, 0.00602056, 0.00639339, 0.00717329,
       0.01321275, 0.00853643, 0.00668509, 0.011315  , 0.00618628,
       0.01169755, 0.02313325, 0.00610283, 0.00842135, 0.00436681,
       0.01714469, 0.00489442, 0.00880968, 0.00840732, 0.00848962,
       0.01001603, 0.02052534, 0.00647864, 0.00506971, 0.00851847,
       0.00684065, 0.00543335, 0.01819314, 0.00952948, 0.00571997,
       0.00397581, 0.01120718, 0.00587155, 0.00389574, 0.00477402,
       0.02189696, 0.00744498, 0.00759323, 0.00498502, 0.01046835,
       0.00627189, 0.00739257, 0.00616757, 0.00310588, 0.00663755,
       0.00777853, 0.00763827, 0.01249455, 0.00576858, 0.00543

In [27]:
ilsr_strength/ilsr_strength.sum()

array([0.01595761, 0.02465364, 0.01435528, 0.01018711, 0.01160215,
       0.01538562, 0.00909814, 0.0342776 , 0.02266499, 0.01594566,
       0.02033338, 0.00792053, 0.01692455, 0.01073288, 0.02099381,
       0.00675822, 0.00511985, 0.00812189, 0.03657007, 0.0183859 ,
       0.01398052, 0.01711026, 0.00718943, 0.00667292, 0.01158058,
       0.01615035, 0.01473765, 0.00602056, 0.00639339, 0.00717329,
       0.01321275, 0.00853643, 0.00668509, 0.011315  , 0.00618628,
       0.01169755, 0.02313325, 0.00610283, 0.00842135, 0.00436681,
       0.01714469, 0.00489442, 0.00880968, 0.00840732, 0.00848962,
       0.01001603, 0.02052534, 0.00647864, 0.00506971, 0.00851847,
       0.00684065, 0.00543335, 0.01819314, 0.00952948, 0.00571997,
       0.00397581, 0.01120718, 0.00587155, 0.00389574, 0.00477402,
       0.02189696, 0.00744498, 0.00759323, 0.00498502, 0.01046835,
       0.00627189, 0.00739257, 0.00616757, 0.00310588, 0.00663755,
       0.00777853, 0.00763827, 0.01249455, 0.00576858, 0.00543

In [28]:
scaling_strength/scaling_strength.sum() - ilsr_strength/ilsr_strength.sum()

array([ 1.92244137e-12, -1.66799526e-11,  1.53307401e-12,  2.43821109e-12,
        2.86788301e-12,  1.04466436e-12,  4.33328373e-12, -7.55863219e-11,
       -9.39173392e-12,  1.25729635e-12, -4.67793859e-12,  4.82421915e-12,
       -4.07708589e-12,  4.43435219e-12, -7.14326168e-12,  4.08038360e-12,
        3.52201168e-12,  3.43345144e-12, -9.93857288e-11, -2.18186233e-12,
        1.72943430e-12, -9.71899644e-13,  3.71034280e-12,  4.54696437e-12,
        2.12705721e-12, -2.07664788e-12, -1.60520208e-12,  4.21654291e-12,
        4.66184903e-12,  4.05176587e-12,  1.13859269e-12,  3.47412377e-12,
        4.76133022e-12,  1.30079628e-12,  3.71373245e-12,  3.80715424e-12,
       -1.76407361e-11,  4.73034893e-12,  4.07087385e-12,  3.53970759e-12,
       -2.12591750e-12,  3.64506082e-12,  5.74858564e-12,  3.70592446e-12,
        4.79428129e-12,  4.55408801e-12, -4.81947468e-12,  4.59937904e-12,
        3.30268538e-12,  4.15035020e-12,  3.36132684e-12,  4.04547663e-12,
       -6.93192725e-12,  