In [1]:
import numpy as np
import pandas as pd

In [2]:
data_1 = pd.read_csv('comedy_comparisons.train', sep=",", header=None)

In [3]:
data_1 

0            1      2
0       sNabaB-eb3Y  wHkPb68dxEw   left
1       sNabaB-eb3Y  y2emSXSE-N4   left
2       fY_FQMQpjok  sNabaB-eb3Y   left
3       Vr4D8xO2lBY  sNabaB-eb3Y  right
4       sNabaB-eb3Y  dDtRnstrefE   left
5       wSMh4E3xxdw  fY_FQMQpjok  right
6       fY_FQMQpjok  No-ZR7-X76s   left
7       HZPUQQNRvOg  2ruyMxxfAJg  right
8       vX95JgKGu0o  wu4SU70w7LA   left
9       sNabaB-eb3Y  2FHH-9teZP0   left
10      sP3YdfG_Uio  fY_FQMQpjok  right
11      fY_FQMQpjok  -AZsrDqF83A   left
12      fY_FQMQpjok  DqEJS86_iUA   left
13      SG2B7dIqbNQ  sNabaB-eb3Y  right
14      rhjIStU0JvI  sNabaB-eb3Y  right
15      axZ2xvYhOKw  vX95JgKGu0o   left
16      fY_FQMQpjok  a-syzH14WQA   left
17      axZ2xvYhOKw  TgrUs_ZwwDc   left
18      bfU4rTa-PfQ  jpntOJ_xDJ0  right
19      Lr4SS1zxRYg  QwpWaLrDHnU   left
20      wvybYNEDQWE  fY_FQMQpjok  right
21      Ai6DSPPo0VI  axZ2xvYhOKw  right
22      g6lJ2k3TCFg  Lr4SS1zxRYg  right
23      Lr4SS1zxRYg  fY_FQMQpjok   left
24      Lr4SS1zxRYg  fY_FQMQpjok   left
25      Lr4SS1zxRYg  axZ2xvYhOKw  right
26      UPTrASEx_p8  axZ2xvYhOKw  right
27      g2HylVyOyzc  plieAqK2a00  right
28      JmtITSojOF8  plieAqK2a00  right
29      BXPvq89jMUg  plieAqK2a00  right
...             ...          ...    ...
912939  7zCIRPQ8qWc  XIPhUZZBtsc   left
912940  ggjT5_JE-DE  MC3mJdfWK70   left
912941  bOcugYjrvLg  6utE5APd4wA  right
912942  q-7HxUScR00  GPxnUrZCtx0  right
912943  hI6D4bynjW4  W9y6nwBwwyQ   left
912944  Z2cpqRpiTqk  oPDM1BjwZg8   left
912945  ggjT5_JE-DE  FgIUryRxGM4   left
912946  LLaKkC5U9Po  wDx28Y2RcCI   left
912947  xjKXcKfjK7c  1Y-Au-tnBLs  right
912948  1Y-Au-tnBLs  xjKXcKfjK7c   left
912949  u2-od4n5Xl0  FgIUryRxGM4  right
912950  W9y6nwBwwyQ  XBqpdx4Dt04  right
912951  t4KvXsglvMg  XXlthnpE-1o   left
912952  wDx28Y2RcCI  FMhrCoyeRVI  right
912953  VWCjVcH1ojs  LLaKkC5U9Po   left
912954  bOcugYjrvLg  6L78MVrd14c   left
912955  ar0G-EcJDnw  XXlthnpE-1o   left
912956  3t_HUglUPLw  1Y-Au-tnBLs  right
912957  3t_HUglUPLw  1Y-Au-tnBLs  right
912958  W9y6nwBwwyQ  XIPhUZZBtsc   left
912959  W9y6nwBwwyQ  bOcugYjrvLg  right
912960  1Y-Au-tnBLs  xjKXcKfjK7c   left
912961  oPDM1BjwZg8  MC3mJdfWK70  right
912962  uvOandCCRFg  Z_hwMtG2xCs  right
912963  MC3mJdfWK70  W9y6nwBwwyQ  right
912964  FgIUryRxGM4  X1hz0RKKzpQ   left
912965  W9y6nwBwwyQ  Z2cpqRpiTqk  right
912966  oPDM1BjwZg8  Z2cpqRpiTqk  right
912967  6utE5APd4wA  t4KvXsglvMg  right
912968  W9y6nwBwwyQ  t4KvXsglvMg  right

[912969 rows x 3 columns]

In [4]:
data_2 = pd.read_csv('comedy_comparisons.test', sep=",", header=None)
data_2

0            1      2
0       7VvBnz1Ngi4  1Y-Au-tnBLs  right
1       6L78MVrd14c  7zCIRPQ8qWc  right
2       bOcugYjrvLg  l92jFP4hvUw  right
3       mr8KrF8vNPM  5hgpAdPDLtc   left
4       bOcugYjrvLg  X1hz0RKKzpQ   left
5       l92jFP4hvUw  MC3mJdfWK70  right
6       75UqLnGK4RI  -_QnmkzFlO0   left
7       u2-od4n5Xl0  6L78MVrd14c   left
8       VWCjVcH1ojs  6L78MVrd14c   left
9       tG6CujNS6J0  mr8KrF8vNPM   left
10      bOcugYjrvLg  0MD6Cx0qzRA   left
11      0Y-hZJ7jAQ4  6nYCKz1DgKI  right
12      MC3mJdfWK70  uvOandCCRFg   left
13      u2-od4n5Xl0  6L78MVrd14c  right
14      FRnBjxVveN4  75UqLnGK4RI  right
15      QL5L-ksQjoU  d6OxBp2fEig   left
16      XXlthnpE-1o  MC3mJdfWK70  right
17      FMhrCoyeRVI  MC3mJdfWK70  right
18      hI6D4bynjW4  7zCIRPQ8qWc   left
19      tG6CujNS6J0  6utE5APd4wA  right
20      Uy5V1PDbyoo  Cou1fP4PoGs  right
21      x5F0A2B8fmU  hC1ieO6mNPw   left
22      ggjT5_JE-DE  6hIs3xFvalI   left
23      MC3mJdfWK70  7zCIRPQ8qWc   left
24      HX9sqE9zBDc  OFG4isKW5mY   left
25      SrB6BCwlTMM  K2cRvoDoGBA  right
26      fPmWfHy97OU  cmTGGpb5_Cw  right
27      LJaGUmjlGuc  Ydsuf37_Auo  right
28      t4KvXsglvMg  XBqpdx4Dt04  right
29      LK379T5gQSA  CyafIfZz9jo  right
...             ...          ...    ...
225563  vZxL0jcVu9s  3t_HUglUPLw   left
225564  xn9HfGvbrpU  PSP2o6FHil8   left
225565  Z2cpqRpiTqk  8It5RVvGCUE   left
225566  3Hm3UjL9kZc  BEnKLhi83J8   left
225567  EOfy5LDpEHo  i6PP451nDPQ   left
225568  e1B3gq8m2Io  JUs8wYFWtA8  right
225569  xfPLiMbfOmY  uLV84xQEvhw  right
225570  xfPLiMbfOmY  nb9Y2kBfO54  right
225571  Z2cpqRpiTqk  OaJZYMXx8X4   left
225572  -iuk0PbfaHY  ezBwuCfpUNE  right
225573  Qh0G7t_ZDB4  ad18HMJRvkI   left
225574  3t_HUglUPLw  Z2cpqRpiTqk  right
225575  xn9HfGvbrpU  3t_HUglUPLw   left
225576  xn9HfGvbrpU  uLV84xQEvhw   left
225577  PSP2o6FHil8  X1hz0RKKzpQ   left
225578  CCvN_ehHPVc  2ofl8hI5bI4  right
225579  41e6ZPR_Uts  0QG3Uwyj15I  right
225580  PQaNWphiu_k  OaJZYMXx8X4  right
225581  wDx28Y2RcCI  vZxL0jcVu9s  right
225582  PQaNWphiu_k  OaJZYMXx8X4   left
225583  Sqh-_2LhXBk  ucGSXtrxnRk  right
225584  xn9HfGvbrpU  vZxL0jcVu9s  right
225585  Z2cpqRpiTqk  vZxL0jcVu9s   left
225586  j-HNsd_mcuY  Qez24F_4YGc  right
225587  wDx28Y2RcCI  xn9HfGvbrpU  right
225588  ELwqCy9NFa4  xfPLiMbfOmY  right
225589  OaJZYMXx8X4  Z2cpqRpiTqk  right
225590  hJT6V_XrTh0  d-wlpSNZzTQ   left
225591  QSJQbDnROXs  Y9mMgn3ZEzA   left
225592  gDqYs1YYG3Y  d-wlpSNZzTQ  right

[225593 rows x 3 columns]

In [5]:
data = data_1.append(data_2)
data

0            1      2
0       sNabaB-eb3Y  wHkPb68dxEw   left
1       sNabaB-eb3Y  y2emSXSE-N4   left
2       fY_FQMQpjok  sNabaB-eb3Y   left
3       Vr4D8xO2lBY  sNabaB-eb3Y  right
4       sNabaB-eb3Y  dDtRnstrefE   left
5       wSMh4E3xxdw  fY_FQMQpjok  right
6       fY_FQMQpjok  No-ZR7-X76s   left
7       HZPUQQNRvOg  2ruyMxxfAJg  right
8       vX95JgKGu0o  wu4SU70w7LA   left
9       sNabaB-eb3Y  2FHH-9teZP0   left
10      sP3YdfG_Uio  fY_FQMQpjok  right
11      fY_FQMQpjok  -AZsrDqF83A   left
12      fY_FQMQpjok  DqEJS86_iUA   left
13      SG2B7dIqbNQ  sNabaB-eb3Y  right
14      rhjIStU0JvI  sNabaB-eb3Y  right
15      axZ2xvYhOKw  vX95JgKGu0o   left
16      fY_FQMQpjok  a-syzH14WQA   left
17      axZ2xvYhOKw  TgrUs_ZwwDc   left
18      bfU4rTa-PfQ  jpntOJ_xDJ0  right
19      Lr4SS1zxRYg  QwpWaLrDHnU   left
20      wvybYNEDQWE  fY_FQMQpjok  right
21      Ai6DSPPo0VI  axZ2xvYhOKw  right
22      g6lJ2k3TCFg  Lr4SS1zxRYg  right
23      Lr4SS1zxRYg  fY_FQMQpjok   left
24      Lr4SS1zxRYg  fY_FQMQpjok   left
25      Lr4SS1zxRYg  axZ2xvYhOKw  right
26      UPTrASEx_p8  axZ2xvYhOKw  right
27      g2HylVyOyzc  plieAqK2a00  right
28      JmtITSojOF8  plieAqK2a00  right
29      BXPvq89jMUg  plieAqK2a00  right
...             ...          ...    ...
225563  vZxL0jcVu9s  3t_HUglUPLw   left
225564  xn9HfGvbrpU  PSP2o6FHil8   left
225565  Z2cpqRpiTqk  8It5RVvGCUE   left
225566  3Hm3UjL9kZc  BEnKLhi83J8   left
225567  EOfy5LDpEHo  i6PP451nDPQ   left
225568  e1B3gq8m2Io  JUs8wYFWtA8  right
225569  xfPLiMbfOmY  uLV84xQEvhw  right
225570  xfPLiMbfOmY  nb9Y2kBfO54  right
225571  Z2cpqRpiTqk  OaJZYMXx8X4   left
225572  -iuk0PbfaHY  ezBwuCfpUNE  right
225573  Qh0G7t_ZDB4  ad18HMJRvkI   left
225574  3t_HUglUPLw  Z2cpqRpiTqk  right
225575  xn9HfGvbrpU  3t_HUglUPLw   left
225576  xn9HfGvbrpU  uLV84xQEvhw   left
225577  PSP2o6FHil8  X1hz0RKKzpQ   left
225578  CCvN_ehHPVc  2ofl8hI5bI4  right
225579  41e6ZPR_Uts  0QG3Uwyj15I  right
225580  PQaNWphiu_k  OaJZYMXx8X4  right
225581  wDx28Y2RcCI  vZxL0jcVu9s  right
225582  PQaNWphiu_k  OaJZYMXx8X4   left
225583  Sqh-_2LhXBk  ucGSXtrxnRk  right
225584  xn9HfGvbrpU  vZxL0jcVu9s  right
225585  Z2cpqRpiTqk  vZxL0jcVu9s   left
225586  j-HNsd_mcuY  Qez24F_4YGc  right
225587  wDx28Y2RcCI  xn9HfGvbrpU  right
225588  ELwqCy9NFa4  xfPLiMbfOmY  right
225589  OaJZYMXx8X4  Z2cpqRpiTqk  right
225590  hJT6V_XrTh0  d-wlpSNZzTQ   left
225591  QSJQbDnROXs  Y9mMgn3ZEzA   left
225592  gDqYs1YYG3Y  d-wlpSNZzTQ  right

[1138562 rows x 3 columns]

In [6]:
idx = data[2]=='right'
data.loc[idx,[0,1]] = data.loc[idx,[1,0]].values
data = data.drop(columns=[2])
data

0            1
0       sNabaB-eb3Y  wHkPb68dxEw
1       sNabaB-eb3Y  y2emSXSE-N4
2       fY_FQMQpjok  sNabaB-eb3Y
3       sNabaB-eb3Y  Vr4D8xO2lBY
4       sNabaB-eb3Y  dDtRnstrefE
5       fY_FQMQpjok  wSMh4E3xxdw
6       fY_FQMQpjok  No-ZR7-X76s
7       2ruyMxxfAJg  HZPUQQNRvOg
8       vX95JgKGu0o  wu4SU70w7LA
9       sNabaB-eb3Y  2FHH-9teZP0
10      fY_FQMQpjok  sP3YdfG_Uio
11      fY_FQMQpjok  -AZsrDqF83A
12      fY_FQMQpjok  DqEJS86_iUA
13      sNabaB-eb3Y  SG2B7dIqbNQ
14      sNabaB-eb3Y  rhjIStU0JvI
15      axZ2xvYhOKw  vX95JgKGu0o
16      fY_FQMQpjok  a-syzH14WQA
17      axZ2xvYhOKw  TgrUs_ZwwDc
18      jpntOJ_xDJ0  bfU4rTa-PfQ
19      Lr4SS1zxRYg  QwpWaLrDHnU
20      fY_FQMQpjok  wvybYNEDQWE
21      axZ2xvYhOKw  Ai6DSPPo0VI
22      Lr4SS1zxRYg  g6lJ2k3TCFg
23      Lr4SS1zxRYg  fY_FQMQpjok
24      Lr4SS1zxRYg  fY_FQMQpjok
25      axZ2xvYhOKw  Lr4SS1zxRYg
26      axZ2xvYhOKw  UPTrASEx_p8
27      plieAqK2a00  g2HylVyOyzc
28      plieAqK2a00  JmtITSojOF8
29      plieAqK2a00  BXPvq89jMUg
...             ...          ...
225563  vZxL0jcVu9s  3t_HUglUPLw
225564  xn9HfGvbrpU  PSP2o6FHil8
225565  Z2cpqRpiTqk  8It5RVvGCUE
225566  3Hm3UjL9kZc  BEnKLhi83J8
225567  EOfy5LDpEHo  i6PP451nDPQ
225568  JUs8wYFWtA8  e1B3gq8m2Io
225569  uLV84xQEvhw  xfPLiMbfOmY
225570  nb9Y2kBfO54  xfPLiMbfOmY
225571  Z2cpqRpiTqk  OaJZYMXx8X4
225572  ezBwuCfpUNE  -iuk0PbfaHY
225573  Qh0G7t_ZDB4  ad18HMJRvkI
225574  Z2cpqRpiTqk  3t_HUglUPLw
225575  xn9HfGvbrpU  3t_HUglUPLw
225576  xn9HfGvbrpU  uLV84xQEvhw
225577  PSP2o6FHil8  X1hz0RKKzpQ
225578  2ofl8hI5bI4  CCvN_ehHPVc
225579  0QG3Uwyj15I  41e6ZPR_Uts
225580  OaJZYMXx8X4  PQaNWphiu_k
225581  vZxL0jcVu9s  wDx28Y2RcCI
225582  PQaNWphiu_k  OaJZYMXx8X4
225583  ucGSXtrxnRk  Sqh-_2LhXBk
225584  vZxL0jcVu9s  xn9HfGvbrpU
225585  Z2cpqRpiTqk  vZxL0jcVu9s
225586  Qez24F_4YGc  j-HNsd_mcuY
225587  xn9HfGvbrpU  wDx28Y2RcCI
225588  xfPLiMbfOmY  ELwqCy9NFa4
225589  Z2cpqRpiTqk  OaJZYMXx8X4
225590  hJT6V_XrTh0  d-wlpSNZzTQ
225591  QSJQbDnROXs  Y9mMgn3ZEzA
225592  d-wlpSNZzTQ  gDqYs1YYG3Y

[1138562 rows x 2 columns]

In [7]:
s0 = pd.Series(data[0])
s1 = pd.Series(data[1])
stacked = pd.concat([s0,s1])
catify = stacked.astype('category')

In [8]:
catify

0         sNabaB-eb3Y
1         sNabaB-eb3Y
2         fY_FQMQpjok
3         sNabaB-eb3Y
4         sNabaB-eb3Y
5         fY_FQMQpjok
6         fY_FQMQpjok
7         2ruyMxxfAJg
8         vX95JgKGu0o
9         sNabaB-eb3Y
10        fY_FQMQpjok
11        fY_FQMQpjok
12        fY_FQMQpjok
13        sNabaB-eb3Y
14        sNabaB-eb3Y
15        axZ2xvYhOKw
16        fY_FQMQpjok
17        axZ2xvYhOKw
18        jpntOJ_xDJ0
19        Lr4SS1zxRYg
20        fY_FQMQpjok
21        axZ2xvYhOKw
22        Lr4SS1zxRYg
23        Lr4SS1zxRYg
24        Lr4SS1zxRYg
25        axZ2xvYhOKw
26        axZ2xvYhOKw
27        plieAqK2a00
28        plieAqK2a00
29        plieAqK2a00
             ...     
225563    3t_HUglUPLw
225564    PSP2o6FHil8
225565    8It5RVvGCUE
225566    BEnKLhi83J8
225567    i6PP451nDPQ
225568    e1B3gq8m2Io
225569    xfPLiMbfOmY
225570    xfPLiMbfOmY
225571    OaJZYMXx8X4
225572    -iuk0PbfaHY
225573    ad18HMJRvkI
225574    3t_HUglUPLw
225575    3t_HUglUPLw
225576    uLV84xQEvhw
225577    

In [9]:
code = catify.cat.codes

In [10]:
code

0         18681
1         18681
2         14414
3         18681
4         18681
5         14414
6         14414
7          1313
8         19721
9         18681
10        14414
11        14414
12        14414
13        18681
14        18681
15        12905
16        14414
17        12905
18        15789
19         7633
20        14414
21        12905
22         7633
23         7633
24         7633
25        12905
26        12905
27        17763
28        17763
29        17763
          ...  
225563     1662
225564     8770
225565     3138
225566     4152
225567    15278
225568    13918
225569    20413
225570    20413
225571     8494
225572      246
225573    12762
225574     1662
225575     1662
225576    19316
225577    11318
225578     4470
225579     1701
225580     8762
225581    19915
225582     8494
225583     9940
225584    20458
225585    19732
225586    15541
225587    19915
225588     5149
225589     8494
225590    13605
225591    11630
225592    14648
Length: 2277124, dtype: 

In [11]:
matrix = np.zeros((1138562,2))

In [12]:
matrix[:,0] = code.iloc[0:1138562]

In [13]:
matrix[:,1] = code.iloc[1138562:]

In [14]:
matrix.min()

0.0

In [15]:
matrix.max()

21206.0

In [16]:
matrix

array([[18681., 19936.],
       [18681., 20564.],
       [14414., 18681.],
       ...,
       [15025., 13605.],
       [ 9108., 11630.],
       [13605., 14648.]])

In [17]:
matrix.shape

(1138562, 2)

In [18]:
#We have obtained comparisons in the form of IDs starting from 0 up to 21206.
#Now convert this to tuples of rankings. 

In [19]:
matrix = matrix.astype(int)
np.savetxt('youtube_raw.txt',matrix,delimiter=',',fmt='%d')

In [ ]:
# below is scrach, may continue to the MLE notebook

In [20]:
matrix = matrix[:50000,:]

In [21]:
import networkx as nx

In [22]:
matrix.shape

(50000, 2)

In [23]:
G = nx.DiGraph()

In [24]:
#build ranking data, need to select largest strongly connected component
rankings = list(map(tuple, matrix))

In [25]:
rankings

[(18681, 19936),
 (18681, 20564),
 (14414, 18681),
 (18681, 10924),
 (18681, 13680),
 (14414, 19994),
 (14414, 8230),
 (1313, 6214),
 (19721, 20164),
 (18681, 1084),
 (14414, 18690),
 (14414, 60),
 (14414, 4999),
 (18681, 9724),
 (18681, 18430),
 (12905, 19721),
 (14414, 12544),
 (12905, 10226),
 (15789, 13130),
 (7633, 9262),
 (14414, 20178),
 (12905, 3986),
 (7633, 14612),
 (7633, 14414),
 (7633, 14414),
 (12905, 7633),
 (12905, 10442),
 (17763, 14584),
 (17763, 6975),
 (17763, 4248),
 (15998, 18789),
 (17763, 20031),
 (12597, 17763),
 (15998, 11736),
 (17469, 17763),
 (12597, 10),
 (12597, 13742),
 (1938, 20826),
 (12597, 13083),
 (12597, 17469),
 (7168, 17469),
 (17469, 17708),
 (1938, 15628),
 (3788, 6110),
 (12597, 10578),
 (7168, 10578),
 (15998, 11424),
 (15998, 13590),
 (7168, 5277),
 (8219, 1369),
 (12597, 7168),
 (15998, 1414),
 (15998, 1414),
 (15998, 13794),
 (15998, 999),
 (17013, 1094),
 (8219, 8976),
 (1938, 15467),
 (1938, 18141),
 (12597, 15998),
 (12597, 15998),
 (15

In [26]:
G.add_edges_from(rankings)

In [27]:
G = max(nx.strongly_connected_component_subgraphs(G), key=len)

In [28]:
Adjacency = nx.adjacency_matrix(G)

In [29]:
Adjacency = Adjacency.toarray()

In [30]:
p = np.sum(Adjacency,1)

In [31]:
n = np.sum(Adjacency)

In [32]:
m = Adjacency.shape[0]

In [33]:
A = np.zeros((n,m))

In [34]:
#np.squeeze((Adjacency[1,:]==1).toarray())

In [35]:
index = 0
for i in range(m):
    length = np.sum(Adjacency[i,:])
    pair = np.where(Adjacency[i,:]==1)[0]
    A[index:index+length,i] = 1
    A[np.arange(index,index+length),pair] = 1
    index += length
    print(A)

[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ...

[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ...

[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ...

[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ...

[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ...

[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ...

[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ...

[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ...

[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ...

[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ...

 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ..

[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ...

[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ...

[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ...

 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ..

[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ...

 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ..

 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ..

[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ...

[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ...

 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ..

[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ...

 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ..

 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ..

[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ...

In [37]:
sum(A[:,1])

25.0

In [38]:
A

array([[1., 1., 0., ..., 0., 0., 0.],
       [1., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [40]:
sum(Adjacency[1,:])

15

In [41]:
Adjacency

array([[0, 1, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)

In [44]:
list(G.edges())

[(18681, 19936),
 (18681, 20564),
 (18681, 10924),
 (18681, 13680),
 (18681, 1084),
 (18681, 9724),
 (18681, 18430),
 (18681, 1782),
 (18681, 13806),
 (18681, 5829),
 (18681, 18671),
 (18681, 13462),
 (18681, 391),
 (18681, 3687),
 (18681, 6812),
 (18681, 14072),
 (18681, 12499),
 (18681, 6549),
 (18681, 6403),
 (18681, 20695),
 (18681, 13063),
 (18681, 16224),
 (18681, 17312),
 (18681, 15203),
 (18681, 11058),
 (18681, 10974),
 (18681, 12047),
 (18681, 15068),
 (18681, 15655),
 (18681, 14686),
 (18681, 17922),
 (18681, 7068),
 (18681, 15322),
 (18681, 5166),
 (18681, 14102),
 (18681, 7972),
 (18681, 12246),
 (18681, 5584),
 (18681, 17374),
 (18681, 15974),
 (18681, 18327),
 (19936, 20298),
 (19936, 4485),
 (19936, 7673),
 (19936, 5929),
 (19936, 5573),
 (19936, 687),
 (19936, 13421),
 (19936, 16676),
 (19936, 17608),
 (19936, 1251),
 (19936, 9603),
 (19936, 1874),
 (19936, 8456),
 (19936, 918),
 (19936, 1901),
 (20564, 7004),
 (20564, 19492),
 (20564, 10659),
 (20564, 9131),
 (20564, 